/// Generic Dimensions
const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_CARD_MEDIUM_2 = 12.0;
const MARGIN_MEDIUM_2 = 16.0;
const MARGIN_MEDIUM_3 = 20.0;
const MARGIN_LARGE = 24.0;
const MARGIN_XLARGE = 32.0;
const MARGIN_XXLARGE = 48.0;

const TEXT_SMALL = 10.0;
const TEXT_REGULAR = 14.0;
const TEXT_REGULAR_2X = 16.0;
const TEXT_REGULAR_3X = 20.0;
const TEXT_HEADING_1X = 24.0;
const TEXT_HEADING_2X = 28.0;
const TEXT_BIG = 32.0;

/// App Specific
const double PROFILE_IAMGE_SIZE = 56.0;

const MOVIE_LIST_VIEW_HEIGHT = 290.0;
const MOVIE_LIST_ITEM_WIDTH = 160.0;
const MOVIE_IMAGE_HEIGHT = 210.0;
const MOVIE_DETAILS_SLIVER_APP_BAR_HEIGHT = 320.0;
const MOVIE_PLAY_BUTTON_SIZE = 60.0;
const MOVIE_DETAILS_CAST_LIST_HEIGHT = 100.0;
const double MOVIE_TIME_DATE_LIST_HEIGHT = 88.0;
const BARCODE_HEIGHT = 100;
const BARCODE_WIDTH = 250;