// Hive Types
// const int HIVE_TYPE_ID_AUTHENTICATION_VO = 1;
const int HIVE_TYPE_ID_CARD_VO = 2;
const int HIVE_TYPE_ID_USER_VO = 3;
const int HIVE_TYPE_ID_MOVIE_VO = 4;
const int HIVE_TYPE_ID_COLLECTION_VO = 5;
const int HIVE_TYPE_ID_GENRE_VO = 6;
const int HIVE_TYPE_ID_PRODUCTION_COMPANY_VO = 7;
const int HIVE_TYPE_ID_PRODUCTION_COUNTRY_VO = 8;
const int HIVE_TYPE_ID_SPOKEN_LANGUAGE_VO = 9;
const int HIVE_TYPE_ID_ACTOR_VO = 10;
const int HIVE_TYPE_ID_DATE_VO = 11;
const int HIVE_TYPE_ID_SNACK_VO = 12;
const int HIVE_TYPE_ID_CINEMA_VO = 13;
const int HIVE_TYPE_ID_TIME_SLOT_VO = 14;
const int HIVE_TYPE_ID_CINEMA_LIST_FOR_HIVE = 15;
const int HIVE_TYPE_ID_PAYMENT_METHOD_FOR_HIVE = 16;


// Box Names
const String BOX_NAME_USER_VO = "BOX_NAME_USER_VO";
const String BOX_NAME_MOVIE_VO = "BOX_NAME_MOVIE_VO";
const String BOX_NAME_SNACK_VO = "BOX_NAME_SNACK_VO";
const String BOX_NAME_CINEMA_VO = "BOX_NAME_CINEMA_VO";
const String BOX_NAME_CINEMA_VO_FOR_HIVE = "BOX_NAME_CINEMA_VO_FOR_HIVE";
const String BOX_NAME_PAYMENT_METHOD_VO = "BOX_NAME_PAYMENT_METHOD_VO";